name 'cerny_nfs'
maintainer 'Nathan Cerny'
maintainer_email 'ncerny@gmail.com'
license 'apache2'
description 'Installs/Configures cerny_nfs'
long_description 'Installs/Configures cerny_nfs'
version '0.4.0'

depends 'nfs'
depends 'firewalld'
depends 'sysctl'
